### ISSUE TITLE
Invalid Request Id

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#29]
Dear @AndreasFagschlunger 

As i can see in old version of O2 and the API in XFSCommand the execute method does not return request id, and some time I get this exception:

WFS_ERR_INVALID_REQ_ID(-27)
	at at.o2xfs.xfs.XfsServiceExceptionFactory.throwException(XfsServiceExceptionFactory.java:52) ~[O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.XfsException.throwFor(XfsException.java:103) ~[O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.XfsAPI.wfsCancelAsyncRequest(XfsAPI.java:77) ~[O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.service.XfsServiceManager.cancel(XfsServiceManager.java:259) ~[O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.service.cmd.XfsCommand.cancel(XfsCommand.java:91) ~[O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.service.RequestQueue.cancelRequest(RequestQueue.java:96) ~[O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.service.XfsRequestWatchdog.checkRequests(XfsRequestWatchdog.java:161) [O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.service.XfsRequestWatchdog.watchOut(XfsRequestWatchdog.java:117) [O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.service.XfsRequestWatchdog.access$0(XfsRequestWatchdog.java:96) [O2Xfs.1.6.5.jar:na]
	at at.o2xfs.xfs.service.XfsRequestWatchdog$1.run(XfsRequestWatchdog.java:84) [O2Xfs.1.6.5.jar:na]

what is it for?
should i return the request id to caller and check it against null (in case of returning null instead of invalid request id exception) ?

**Comment by pouyamoradian** [comment]
Any suggestion ?

**Comment by AndreasFagschlunger** [comment]
The `WFSCancelAsyncRequest` seems to be executed within `XfsRequestWatchdog`. The purpose of `XfsRequestWatchdog` is to guard against hanging SPI. It does only apply to commands which specify a timeout. When you specify a timeout and the command doesn't finish in time, the XFS Manager should send a `WFS_*_COMPLETE` message where the result is `WFS_ERR_TIMEOUT`.

So the request is added to the Watchdog after `WFSAsync*` returned and removed when `WFS_*_COMPLETE` message arrived.

But what seems to happen is, that although the timeout is over no complete message arrived. This should not happen if SPI and XFS Manager work correctly. But if this happens, your (customer) application may also hang - since you wait for the command to complete (either successfully or with `ERR_TIMEOUT`).

To compensate for this wrong behavior, the Watchdog checks the timeout for itself. If it's over and still no complete message arrives, it executes a `WFSCancelAsyncRequest` command. In your case, this command fails with `INVALID_REQ_ID`. The next time the WatchDog checks the request, it detects the command is still active although it should had been cancelled by now. So it creates a `ERR_CANCELED` result and sends this information to the application. This way the application can move on, where the command is till active on XFS level.

The log files should point out which request(-ID) doesn't complete. So try to figure out what happens to this particular request. You should check the SPI logs to trace the command to, maybe the SPI sends a complete message but other things went wrong.

**Comment by pouyamoradian** [comment]
I've got it, thanks for your clear description.

**Comment by pouyamoradian** [comment]
Hi again @AndreasFagschlunger 
I hope you're doing well.

As I received some log file, there is some InterruptedExceptio in watchOut() on XfsRequestWatchdog, and i see watch dog thread start once in XfsRequestWatchdog.start(), it means after that there is no watch dog thread.

What is your solution for this situation ?
Should i restart the watch Dog thread again ? (on InterruptedException).
It may become unstoppable.
And also i didn't get that why I'm getting InterruptedException!

With best regards
Pouya Moradian

**Comment by pouyamoradian** [comment]
The log is something like this

INFO  2016-08-17 09:39:35,791- - : -  - at.o2xfs.xfs.service.XfsRequestWatchdog - watchOut(): Interrupted 
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_74]
	at java.lang.Object.wait(Unknown Source) ~[na:1.8.0_74]
	at at.o2xfs.xfs.service.XfsRequestWatchdog.watchOut(XfsRequestWatchdog.java:105) [O2Xfs.1.6.8.jar:na]
	at at.o2xfs.xfs.service.XfsRequestWatchdog.access$0(XfsRequestWatchdog.java:96) [O2Xfs.1.6.8.jar:na]
	at at.o2xfs.xfs.service.XfsRequestWatchdog$1.run(XfsRequestWatchdog.java:84) [O2Xfs.1.6.8.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]
ERROR 2016-08-17 09:39:35,792- - : -  - at.o2xfs.xfs.service.cmd.XfsCallable - call(): Interrupted while waiting 
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_74]
	at java.lang.Object.wait(Unknown Source) ~[na:1.8.0_74]
	at at.o2xfs.xfs.service.cmd.XfsCallable.call(XfsCallable.java:65) ~[O2Xfs.1.6.8.jar:na]
	at at.o2xfs.xfs.service.cmd.XfsCommand.call(XfsCommand.java:101) [O2Xfs.1.6.8.jar:na]
	at at.o2xfs.xfs.service.XfsServiceStartUp.open(XfsServiceStartUp.java:55) [O2Xfs.1.6.8.jar:na]
	at at.o2xfs.xfs.service.XfsServiceStartUp.startUp(XfsServiceStartUp.java:86) [O2Xfs.1.6.8.jar:na]
	at at.o2xfs.xfs.service.XfsServiceManager.openAndRegister(XfsServiceManager.java:156) [O2Xfs.1.6.8.jar:na]

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian The interrupt occurs if you call `XfsServiceManager.shutdown()`, because it would also stop the WatchDog-Thread. No it looks like you attempt to stop and restart the `XfsServiceManager`, since the second Stacktrace comes from `XfsServiceStartUp.startUp`.

At the moment it's true that you can't call `XfsServiceManager.shutdown()` and `XfsServiceManager.initialize()` again, because XfsRequestWatchdog and maybe other Threads are started on construction and not on initialize.

It can and should be fixed, but it's not a common scenario. So do you really want to shutdown and re-initialize XfsServiceManager?

**Comment by pouyamoradian** [comment]
Hi

Well, The answer is no.
As i know there is no mechanism for restarting the device layer in my code, and i didn't know why the interrupt exception occurred !
I'm not a java guy but as i read before the InterruptedException in java may happen in result of calling a callable or runnable method. So as i understand there is no such bad state that may cause InterruptedException in watch dog thread and it may be happen in result of calling shutdown.
Am i right?

**Comment by AndreasFagschlunger** [comment]
Yes, it looks like somewhere `XfsServiceManager.shutdown()` is called which will result in the call to `XfsRequestWatchdog.stop()`. Which then will result in a `InterruptedException` like in the first stacktrace, since `requests` List in `XfsRequestWatchdog` is empty and so `wait()`ing for new requests. If it's not intended to stop the thread, you can log a stacktrace in `stop()` to find who i calling the `stop()` method. It would also reveal if some other thing causes the thread to stop, in which case you really could restart the thread.

**Comment by pouyamoradian** [comment]
That's a good idea,
I'll try it.

Thanks a lot
