### ISSUE TITLE
Operator task PINGetDataTask not work

### ISSUE THREAD

**Issue by jifffffy** [AndreasFagschlunger/O2Xfs#49]
HI , In at.o2xfs.operator.task.xfs.pin.PINGetDataTask#execute() may not work as 
`this.service = service;`

should remove this field?

**Comment by AndreasFagschlunger** [comment]
The line has no effect, so you can delete it but it's probably not the reason the task doesn't work. Can you go into more detail what's wrong? Does the log show errors?

**Comment by jifffffy** [comment]
Hi, Here's the log.

2017-11-22 08:42:53,062 WARN  [AWT-EventQueue-0] at.o2xfs.operator.ui.swing.i18n.Messages: getText(String): Undefined label: MenuTask
2017-11-22 08:42:53,078 WARN  [AWT-EventQueue-0] at.o2xfs.operator.ui.swing.i18n.Messages: getText(String): Undefined label: >
2017-11-22 08:42:53,078 WARN  [AWT-EventQueue-0] at.o2xfs.operator.ui.swing.i18n.Messages: getText(String): Undefined label: >
2017-11-22 08:42:53,078 WARN  [AWT-EventQueue-0] at.o2xfs.operator.ui.swing.i18n.Messages: getText(String): Undefined label: PIN Pad
2017-11-22 08:42:54,421 INFO  [AWT-EventQueue-0] at.o2xfs.operator.ui.swing.menu.MenuButton: actionPerformed(ActionEvent): Pressed: <html>PIN Pad Test</html>
2017-11-22 08:42:54,421 DEBUG [AWT-EventQueue-0] at.o2xfs.operator.task.TaskManager: execute(Task): task=at.o2xfs.operator.task.xfs.pin.PINGetDataTask@30b015,taskPath=[at.o2xfs.operator.menu.MenuTask@10ef7d7]
2017-11-22 08:42:54,421 ERROR [PINGetDataTask] at.o2xfs.operator.task.TaskManager: executeTask(): Exception in Task: at.o2xfs.operator.task.xfs.pin.PINGetDataTask@30b015
java.lang.IllegalArgumentException
	at at.o2xfs.common.Assert.notNull(Assert.java:38)
	at at.o2xfs.xfs.service.cmd.XfsCommand.<init>(XfsCommand.java:54)
	at at.o2xfs.xfs.service.cmd.XfsInfoCommand.<init>(XfsInfoCommand.java:84)
	at at.o2xfs.xfs.service.cmd.XfsInfoCommand.<init>(XfsInfoCommand.java:80)
	at at.o2xfs.xfs.service.pin.cmd.PINFunctionKeysCommand.call(PINFunctionKeysCommand.java:78)
	at at.o2xfs.operator.task.xfs.pin.PINGetDataTask.execute(PINGetDataTask.java:121)
	at at.o2xfs.operator.task.xfs.XfsServiceTask.doExecute(XfsServiceTask.java:73)
	at at.o2xfs.operator.task.Task.execute(Task.java:90)
	at at.o2xfs.operator.task.TaskManager.executeTask(TaskManager.java:148)
	at at.o2xfs.operator.task.TaskManager.access$100(TaskManager.java:39)
	at at.o2xfs.operator.task.TaskManager$1.run(TaskManager.java:136)
	at java.lang.Thread.run(Unknown Source)


If I remove the service field, then is OK.

**Comment by AndreasFagschlunger** [comment]
I see the problem now, `PINGetDataTask` should use `PINService` from it's parent. The local `service` attribute is obsolete and `null`, which leads to the Exception above. I fixed this in `develop` branch.
